---
title: "Combining Data and Analysis"
author: "Daniel Fuller"
date: "2024-05-30"
output:
  html_document:
    keep_md: true
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE, warning = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(reportRmd)
library(ggridges)
```

## Read Data

```{r, warning = FALSE, message = FALSE}
barrhaven <- read_csv("Ottawa/ottawa_barrhaven_bike_transit_drive.csv")
blair <- read_csv("Ottawa/ottawa_blaire_bike_transit_drive.csv")
scar <- read_csv("Toronto/toronto_scarborough_bike_transit_drive.csv")
vaughn <- read_csv("Toronto/toronto_vaughn_bike_transit_drive.csv")
bross <- read_csv("Montreal/montreal_brossard_bike_transit_drive.csv")
rivier <- read_csv("Montreal/montreal_riviereprairie_bike_transit_drive.csv")
mckenzie <- read_csv("Calgary/calgary_mckenzie_bike_transit_drive.csv")
np <- read_csv("Calgary/calgary_northpoint_bike_transit_drive.csv")
heritage <- read_csv("Edmonton/edmonton_heritage_bike_transit_drive.csv")
naki <- read_csv("Edmonton/edmonton_naki_bike_transit_drive.csv")
```

## Joining Data

```{r, warning = FALSE, message = FALSE}
data <- bind_rows(barrhaven, blair, scar, vaughn, bross, rivier, mckenzie, np, heritage, naki)

write_csv(data, file = "mode_city_data.csv")
```

## Summary statistics by mode

```{r, warning = FALSE, message = FALSE}
rm_covsum(data=data, maincov = 'mode',
covs=c('distance_km','duration_hours'))
```

## Summary statistics by station

```{r, warning = FALSE, message = FALSE}
rm_covsum(data=data, maincov = 'station',
covs=c('distance_km','duration_hours'))
```

## Data Viz by time

```{r, warning = FALSE, message = FALSE}
viz <- ggplot(data, aes(x = duration_hours, y = mode, fill = mode)) +
  geom_density_ridges() + 
  stat_density_ridges(quantile_lines = TRUE, alpha = 0.75, quantiles = 2) +
  facet_wrap(~ station)
plot(viz)
```


